language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
before_install:
    - pip install coveralls
install: 
    - pip install -r requirements.txt
# command to run tests
script: 
    - python -m unittest discover --verbose
after_success:
    - if [[ $ENV == python=3.4* ]]; then
          coveralls;
      fi
branches:
  only:
    - master