language: python
python:
  - "3.4.5"
  - "3.5"
  - "3.6"
  - "3.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls

# command to run tests
script:
    - coverage run --source=MyCapytain setup.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi

deploy:
  provider: pypi
  user: ponteineptique
  password: $PYPASS
  on:
    tags: true
    python: "3.5"
