language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
    - pip install -r requirements.txt
    - pip install coveralls

# command to run tests
script:
    - coverage run --source=MyCapytain setup.py test

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi

branches:
  only:
    - master
    - 0.1.0dev
