language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script: 
    - coverage run --source=MyCapytain setup.py test
after_success:
    - if [[ $ENV == python=3.4* ]]; then
          coveralls;
      fi
branches:
  only:
    - master